name: 'test'
description: 'Test sample fastkafka'
inputs:
  version:
    description: 'Version of python to set up'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
    - name: Test
      shell: bash
      run: |
        set -ux
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python test.py
